# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- ci/test-azure-pipelines

pool:
  vmImage: ubuntu-latest

 steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
     repository: test
     command: build
     Dockerfile: docker/builder/Dockerfile
