# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- ci/test-azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo test
  displayName: 'make'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'docker/builder/Dockerfile'
    buildContext: '.'